# Generated by Django 5.2.12 on 2026-03-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('cover_image', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('date', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
